name: ml-agents
dependencies:
  - python=3.7.9
  - cudatoolkit=10.2
  - torchvision
  - pytorch
  - pip=20.3
  - pip: 
    - mlagents==0.23.0
    - mlagents-envs==0.23.0
    - gym_unity==0.23.0
    - isort
    - black
    - mypy
    - autoflake
